# TCL File Generated by Component Editor 18.1
# Sat Jun 15 20:04:38 CST 2024
# MODIFY PATH TO VERILOG FILES ONLY
# ASSUMES YOU CLONED THE REPO TO A FOLDER CALLED IP/FreeCores/ 


# 
# uart_avalon_top "uart16550_freecores" v1.0
# Jacob Gorban 2024.06.15.20:04:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module uart_avalon_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME uart_avalon_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP FreeCores
set_module_property AUTHOR "Jacob Gorban"
set_module_property DISPLAY_NAME uart16550_freecores
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL uart_top_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file raminfr.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/raminfr.v
add_fileset_file uart_debug_if.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_debug_if.v
add_fileset_file uart_defines.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_defines.v
add_fileset_file uart_receiver.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_receiver.v
add_fileset_file uart_regs.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_regs.v
add_fileset_file uart_rfifo.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_rfifo.v
add_fileset_file uart_sync_flops.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_sync_flops.v
add_fileset_file uart_tfifo.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_tfifo.v
add_fileset_file uart_top.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_top.v
add_fileset_file uart_top_avalon.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_top_avalon.v TOP_LEVEL_FILE
add_fileset_file uart_transmitter.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_transmitter.v
add_fileset_file uart_wb.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_wb.v
add_fileset_file timescale.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/timescale.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL uart_top_avalon
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file raminfr.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/raminfr.v
add_fileset_file timescale.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/timescale.v
add_fileset_file uart_debug_if.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_debug_if.v
add_fileset_file uart_defines.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_defines.v
add_fileset_file uart_receiver.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_receiver.v
add_fileset_file uart_regs.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_regs.v
add_fileset_file uart_rfifo.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_rfifo.v
add_fileset_file uart_sync_flops.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_sync_flops.v
add_fileset_file uart_tfifo.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_tfifo.v
add_fileset_file uart_top.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_top.v
add_fileset_file uart_top_avalon.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_top_avalon.v
add_fileset_file uart_transmitter.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_transmitter.v
add_fileset_file uart_wb.v VERILOG PATH IP/FreeCores/uart16550_qsys_ready/rtl/verilog/uart_wb.v


# 
# documentation links
# 
add_documentation_link Spec http://https://github.com/Josfemova/uart16550_qsys_ready/blob/master/doc/UART_spec.pdf


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clk
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point serial_modem
# 
add_interface serial_modem conduit end
set_interface_property serial_modem associatedClock clk
set_interface_property serial_modem associatedReset reset
set_interface_property serial_modem ENABLED true
set_interface_property serial_modem EXPORT_OF ""
set_interface_property serial_modem PORT_NAME_MAP ""
set_interface_property serial_modem CMSIS_SVD_VARIABLES ""
set_interface_property serial_modem SVD_ADDRESS_GROUP ""

add_interface_port serial_modem cts_pad_i cts_pad_i Input 1
add_interface_port serial_modem dcd_pad_i dcd_pad_i Input 1
add_interface_port serial_modem dsr_pad_i dsr_pad_i Input 1
add_interface_port serial_modem dtr_pad_o dtr_pad_o Output 1
add_interface_port serial_modem ri_pad_i ri_pad_i Input 1
add_interface_port serial_modem rts_pad_o rts_pad_o Output 1
add_interface_port serial_modem srx_pad_i srx_pad_i Input 1
add_interface_port serial_modem stx_pad_o stx_pad_o Output 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits SYMBOLS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 1
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 write write Input 1
add_interface_port s1 read read Input 1
add_interface_port s1 address address Input 5
add_interface_port s1 writedata writedata Input 32
add_interface_port s1 byteenable byteenable Input 4
add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 waitrequest waitrequest Output 1
add_interface_port s1 readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

